using System.Collections.Generic;
using UnityEngine;

namespace GameJamUniverse.Core.Minigames
{
    /// <summary>
    /// Flat list of every minigame the Hub can offer. Regenerated by the
    /// "Tools/GameJam/Refresh Minigame Registry" editor command, which scans
    /// Minigames/*/Config/*.asset for <see cref="MinigameMetadata"/> assets - new minigames are
    /// picked up automatically without touching Hub code.
    /// </summary>
    [CreateAssetMenu(fileName = "MinigameRegistry", menuName = "GameJam Universe/Minigame Registry")]
    public class MinigameRegistry : ScriptableObject
    {
        [SerializeField] private List<MinigameMetadata> games = new();

        public IReadOnlyList<MinigameMetadata> Games => games;

        public MinigameMetadata FindById(string gameId)
        {
            for (int i = 0; i < games.Count; i++)
            {
                if (games[i] != null && games[i].gameId == gameId)
                {
                    return games[i];
                }
            }
            return null;
        }

#if UNITY_EDITOR
        /// <summary>Editor-only: used by the registry refresh tool to rewrite the list.</summary>
        public void EditorSetGames(List<MinigameMetadata> newGames)
        {
            games = newGames;
        }
#endif
    }
}
